package Enums;

public enum ChatStateEnum {
    DEFAULT,
    DEFAULT_UNREGISTERED,
    AUCTION,
    AUCTION_UPDATE,
    AUCTION_VIEW,
    AUCTION_DELETE,
    AUCTION_ADD,
    DEFAULT_ACCESS_REQUESTED,
    USERS,
    USERS_DELETE,
    USERS_GRANT_ROOT
}
